### ISSUE TITLE
TODO list for adaptive-hashmap hotcold benchmark

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/adaptive-data#9]
I've been fixing various things about `Bench1.hs`, but there's still a ways to go.
- [x] Need to finish refactoring to use `GenericImpl`
- [x] Need to make sure the client is allocating, even during read phase, for realism.
- [x] Need to use random keys rather than consecutive
  - [x] Computing these keys _inline_ rather than precomputing will help with creating a nontrivial phase2 client workload.
- [x] Need to introduce a keyspace size parameter and get rid of the `mod` hack that's in there ("Temp/HACK modulus").
- [x] Related to previous, it's good for the client to actual use values retrieved via get, for example summing them.
- [x] Probably should make AdaptiveMap use INLINE rather than INLINABLE, because it helps to be certain there.  
- [x] We have two copies of CTrie in there... delete one.

Remaining mysteries/questions: 
- [x] Adaptive does reasonably well (close to pure) for `coldPhase`, but why doesn't `c-adaptive` yet do better?

**Comment by rrnewton** [comment]
Finally, with duplicated code between (1) different benchmark modes, and (2) different data structures it's very hard to remember to update each variant and keep everything apples-to-apples.  Just be careful.

**Comment by rrnewton** [comment]
- [x] Minor bug, passing `--runs=1` to the Bench1 harness results in:

`bench-adaptive-hashmap-1: Prelude.!!: index too large`

**Comment by vikraman** [comment]
adaptive and c-adaptive almost coincide with pure for `coldPhase`, tested at commit  9dee407.
`stack bench adaptive-hashmap:bench-adaptive-hashmap-1 '--benchmark-arguments=--doplot --ops=100000000 --bench=cold --runs=5 --minthreads=1 --maxthreads=12 --ratio=5000 --variants=pure --variants=adaptive --variants=c-adaptive'`
![report](https://cloud.githubusercontent.com/assets/213959/13564460/d49bb114-e417-11e5-948f-0a2f7be6edc4.png)

**Comment by rrnewton** [comment]
Thanks!  Could you post a link to the git revision with the plots?  This is a scenario where we keep updating and tweaking so its good to know which version it came from.

**Comment by rrnewton** [comment]
Since all the checkmarks above are checked off, I was expecting c-adaptive to pull ahead because of some GC savings.. when I can I'll poke at this a bit more to figure out why not.  Definitely need to make sure allocation+GCs are happening during that cold phase

@vikraman, when you get a chance I or someone else can show you how to use threadscope if you haven't already used it.
